//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwimmingPool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int MailNumber { get; set; }
        public string MailTo { get; set; }
        public string Subject { get; set; }
        public string MailBody { get; set; }
        public string Status { get; set; }
    }
}
